server:
  port: 10001
spring:
  datasource: # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis: # 配置redis
    host: 192.168.6.100
    port: 6379
mybatis:
  type-aliases-package: com.shaluy.pojo
logging:
  level:
    com.shalu.dao: debug